version: "3.7"
services:
  chrony:
    build: .
    image: cawad/alpine-chrony:latest
    container_name: ntpd
    restart: unless-stopped
    ports:
      - 123:123/udp # ntp port
      - 323:323/udp # remote monitoring for `chronyc -h <host>`
    cap_add:
      - SYS_NICE
      - SYS_TIME
      - SYS_RESOURCE
